### ISSUE TITLE
Sampling logic error? x-b3-flags / x-b3-sampled logic question

### ISSUE THREAD

**Issue by nwest1** [openzipkin-contrib/zipkin-go-opentracing#104]
Hi-
Quoting https://github.com/openzipkin/b3-propagation/#debug-flag-1
> Debug is encoded as `X-B3-Flags: 1`. Debug implies an accept decision: don't also send `X-B3-Sampled: 1`.

Though https://github.com/openzipkin/zipkin-go-opentracing/blob/master/zipkin-recorder.go#L86 only checks the `Sampled` flag. 

Should there be additional logic added to accept(sample) traces flagged as debug? I can create a PR, but maybe my understanding of this is incorrect.

Thank you!

**Comment by adriancole** [comment]
when https://github.com/openzipkin-contrib/zipkin-go-opentracing/pull/123 is complete, flaws around b3 handling will go away I think

**Comment by basvanbeek** [comment]
Closing as #123 has been merged and now used the B3 propagation package from Zipkin Go.
