### ISSUE TITLE
Is x-b3-flags mandatory?

### ISSUE THREAD

**Issue by xueliangliang** [openzipkin-contrib/zipkin-go-opentracing#106]
https://github.com/openzipkin/zipkin-go-opentracing/blob/6bb822a7f15fdc5800b9822a6ac1bfa0b7d9195d/propagation_ot.go#L29

However for PCF zipkin tracing, it only injects two headers `X-B3-TraceId` and `X-B3-SpanId` for the first hop api endpoint.  [https://docs.cloudfoundry.org/concepts/http-routing.html#-http-headers-for-zipkin-tracing]

**Comment by basvanbeek** [comment]
x-b3-flags is not mandatory so it could be omitted if Debug is false. You're welcome to send a PR.

**Comment by xueliangliang** [comment]
I have created the PR, can it be approved?

**Comment by nmiyake** [comment]
I ran into this issue as well and upon looking at the code found that the extraction code has more general bugs -- I filed #118 to track the general issue and opened the PR #119 to fix it (with tests to verify behavior).
