### ISSUE TITLE
Use correct Thrift import path

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [openzipkin-contrib/zipkin-go-opentracing#111]
Auto-generated Thrift code uses the official import path of `git.apache.org/thrift.git/lib/go/thrift`, but zipkin-go-opentracing uses the GitHub mirror at `github.com/apache/thrift/lib/go/thrift`.  These are _distinctly different_ packages that are similar in contents, but not actually the same: "[An import path is a string that _**uniquely**_ identifies a package.](https://golang.org/doc/code.html#ImportPaths)" (emphasis mine)

For example, this means that structures and other types defined in the GitHub.com mirror are distinctly different from the official package.

I realize this has been raised and discussed in previous issues for this project, but this can lead to some interesting bugs if one is not observant of this fact, such as the example seen below:
```
package main

import (
	"fmt"

	"git.apache.org/thrift.git/lib/go/thrift"
	thrift2 "github.com/apache/thrift/lib/go/thrift"
)

func main() {
	bp := thrift.TBinaryProtocol{}
	var iface interface{} = bp

	_, apache := iface.(thrift.TBinaryProtocol)
	_, github := iface.(thrift2.TBinaryProtocol)

	// will print: apache: true; github: false
	fmt.Printf("apache: %v; github: %v", apache, github)
}
```
The example indicates the `TBinaryProtocol` interface exposed by GitHub is a different type from the official Apache mirror one.

Many of our developers use IntelliJ / GoLand IDE which has autocomplete features.  Some of them are new to Thrift and/or Go and in the past have sometimes accidentally imported the GitHub package instead of the official Apache package.  That puts us at risk of bugs like the one illustrated above.  zipkin-go-opentracing is a blocker for us to purge the github.com mirror package completely, because it forces us to have both Thrift packages present (and therefore available to autocomplete, and therefore a trap waiting to ensnare the unwary user).

Given that auto-generated Thrift code uses `git.apache.org/thrift.git/lib/go/thrift` at https://github.com/apache/thrift/blob/88591e32e710a0524327153c8b629d5b461e35e0/compiler/cpp/src/thrift/generate/t_go_generator.cc#L64 - would zipkin-go-opentracing be open to switching back to the official package given the bugs / code correctness problems that using an alternate mirror package can raise?

**Comment by basvanbeek** [comment]
Closing this as we're now using Zipkin Go v2 exporters now.
