### ISSUE TITLE
Tags are serialized in arbitrary and varying order

### ISSUE THREAD

**Issue by RaduBerinde** [openzipkin-contrib/zipkin-go-opentracing#112]
The opentracing span tags are stored in a map. Zipkin adds them in the arbitrary order in which the iteration returns them: 
https://github.com/openzipkin-contrib/zipkin-go-opentracing/blob/master/zipkin-recorder.go#L169-L171

This causes inconsistent ordering (at least in Jaeger). I propose that we sort the tags so they are added in the same order.

**Comment by basvanbeek** [comment]
Closing this as we're a bridge to Zipkin Go now and do not handle tag serialization anymore
