### ISSUE TITLE
loop in scribe collector infinitely spawns send() goroutines

### ISSUE THREAD

**Issue by bogatuadrian** [openzipkin-contrib/zipkin-go-opentracing#114]
If the `send()` method blocks (e.g. because of network), the `loop()` method continues to spawn goroutines indefinitely. The problem is that the `currentBatchSize >= c.batchSize` condition will always be true if a `send()` is blocked ([collector-scribe.go#L147](https://github.com/openzipkin-contrib/zipkin-go-opentracing/blob/master/collector-scribe.go#L147)).

I think this is a broken behaviour, and could be easily fixed, probably by not allowing another `send()` to be spawned if one is already running. I'm up for doing a PR if the maintainers agree this should be fixed.

**Comment by fho** [comment]
We also run into this issue.
Go-Applications were spawning more and more Go-Routines stuck in:
```
goroutine 15196 [semacquire, 236 minutes]:
sync.runtime_SemacquireMutex(0xc0004102d4, 0x0)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0004102d0)
	/usr/local/go/src/sync/mutex.go:134 +0xff
sisu.sh/go/vendor/github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).send(0xc0004241b0, 0x0, 0x0)
	/workspace/src/sisu.sh/go/vendor/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:192 +0x4f
created by sisu.sh/go/vendor/github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).loop
	/workspace/src/sisu.sh/go/vendor/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:167 +0x273
```
This causes the application to consume more and more memory until they get OOM killed because they use more then they are alllowed.

**Comment by fho** [comment]
Sounds like v0.3.5 contains a fix for the issue:
> Fixed go routine proliferation in http collector.

https://github.com/openzipkin-contrib/zipkin-go-opentracing/releases/tag/v0.3.5

**Comment by basvanbeek** [comment]
Closing this as we now use the V2 transports from Zipkin Go
