### ISSUE TITLE
HTTPCollector. send goroutine only increase without decreasing

### ISSUE THREAD

**Issue by kinwyb** [openzipkin-contrib/zipkin-go-opentracing#117]
goroutine profile: total 231
206 @ 0x4034f04 0x4034fc3 0x40464e3 0x404626d 0x406e3bd 0x4b5e5b4 0x4065341
#	0x404626c	sync.runtime_SemacquireMutex+0x3c					/usr/local/go/src/runtime/sema.go:71
#	0x406e3bc	sync.(*Mutex).Lock+0x25c						/usr/local/go/src/sync/mutex.go:134
#	0x4b5e5b3	github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).send+0x53	/Users/heldiam/Developer/GO/src/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:192

==================================================================

goroutine profile: total 254
229 @ 0x4034f04 0x4034fc3 0x40464e3 0x404626d 0x406e3bd 0x4b5e5b4 0x4065341
#	0x404626c	sync.runtime_SemacquireMutex+0x3c					/usr/local/go/src/runtime/sema.go:71
#	0x406e3bc	sync.(*Mutex).Lock+0x25c						/usr/local/go/src/sync/mutex.go:134
#	0x4b5e5b3	github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).send+0x53	/Users/heldiam/Developer/GO/src/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:192

==================================================================

goroutine profile: total 262
237 @ 0x4034f04 0x4034fc3 0x40464e3 0x404626d 0x406e3bd 0x4b5e5b4 0x4065341
#	0x404626c	sync.runtime_SemacquireMutex+0x3c					/usr/local/go/src/runtime/sema.go:71
#	0x406e3bc	sync.(*Mutex).Lock+0x25c						/usr/local/go/src/sync/mutex.go:134
#	0x4b5e5b3	github.com/openzipkin/zipkin-go-opentracing.(*HTTPCollector).send+0x53	/Users/heldiam/Developer/GO/src/github.com/openzipkin/zipkin-go-opentracing/collector-http.go:192

why goroutine only increase without decreasing

**Comment by fho** [comment]
Seems to be the same issue then https://github.com/openzipkin-contrib/zipkin-go-opentracing/issues/114

**Comment by basvanbeek** [comment]
Closing this as we now use the V2 transports from Zipkin Go
