### ISSUE TITLE
Span extraction fails for valid carriers and succeeds for invalid carriers

### ISSUE THREAD

**Issue by nmiyake** [openzipkin-contrib/zipkin-go-opentracing#118]
There is currently a bug in the `(p *textMapPropagator) Extract` function in `propagation_ot.go`.

The extractor defines the minimum number of required fields that are set to be 3, but carriers only need a trace ID and span ID to be valid (and these values also MUST be present per the [HTTP encodings spec in openzipkin/b3-propagation](https://github.com/openzipkin/b3-propagation/blob/master/README.md#http-encodings), which states that `TraceId` and `SpanId` are required). Thus, the current code improperly rejects carriers that have only these values set (this is the same issue as #106).

The current logic also naively increments the "required field" count on any parsed field -- thus, a carrier that has any 3 fields defined on it is considered valid even when it should not be (for example, a carrier with a parent span ID, "sampled" and "flags" is considered valid because it has 3 fields defined, even though trace ID and span ID are required and not defined).

The extraction code should be updated to require that trace ID and span ID be defined and to allow extraction to succeed for carriers with only those values defined.

The [implementation in `openzipkin/zipkin-go`](https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/spancontext.go) properly handles both of these cases.

**Comment by basvanbeek** [comment]
Closing this issue as tracking B3 extraction issues now with #121
