### ISSUE TITLE
Thrift HttpCollector overflow issues

### ISSUE THREAD

**Issue by Stocco** [openzipkin-contrib/zipkin-go-opentracing#130]
Issue:
    Thrift does not support unsiged integers which leads to traceIds overflow. Example: traceId `eca2a316fcfb1a01` overflows the traceId thrift model int64 becoming negative some number.

Solution:
     I'v made an pr that sends the spans via JSON using a new span struct to afford the new fields as string.

Pr (#129)

**Comment by basvanbeek** [comment]
Closing this as the latest release uses v2 transports from Zipkin Go
