### ISSUE TITLE
failed to inject span: opentracing: Invalid Inject/Extract carrier

### ISSUE THREAD

**Issue by ONG-YA** [openzipkin-contrib/zipkin-go-opentracing#146]
ERROR: failed to inject span: opentracing: Invalid Inject/Extract carrier

when i use the Latest release version of zipkin-opentracing-go, some exception appears.It seems like the new version don't support "TextMapCarrier map[string]string"

```go
func (p *textMapPropagator) Extract(
	opaqueCarrier interface{},
) (opentracing.SpanContext, error) {
	if extractor, ok := opaqueCarrier.(propagation.Extractor); ok {
		sc, err := extractor()
		if sc != nil {
			return SpanContext(*sc), err
		}
		return SpanContext{}, err
	}
	if httpCarrier, ok := opaqueCarrier.(opentracing.HTTPHeadersCarrier); ok {
		req := &http.Request{Header: http.Header(httpCarrier)}
		sc, err := b3.ExtractHTTP(req)()
		if sc != nil {
			return SpanContext(*sc), err
		}
		return SpanContext{}, err
	}
	return nil, opentracing.ErrUnsupportedFormat
}
```

**Comment by jcchavezs** [comment]
I believe this line:
```
if httpCarrier, ok := opaqueCarrier.(opentracing.HTTPHeadersCarrier); ok {
```

should be 
```
if textMapCarrier, ok := opaqueCarrier.(opentracing.TextMapCarrier); ok {
```

Any thoughts @basvanbeek ?

**Comment by basvanbeek** [comment]
Nope... I think there is a good use case for having a map carrier for zipkin go which we could make TextMapCarrier compatible for this bridge

**Comment by jcchavezs** [comment]
Not sure I am following. Correct me if I am wrong, is it that here the issue is that the so called `TextMapCarrier` is expecting a ot.HTTPHeaders instead of it.TextMapCarrier?

**Comment by dayadev** [comment]
I am having the same issue here, [142](https://github.com/openzipkin-contrib/zipkin-go-opentracing/issues/142)

**Comment by basvanbeek** [comment]
@ONG-YA can you check if the latest in master fixes your issue?

**Comment by basvanbeek** [comment]
Closing this issue as TextMapCarrier is not only implemented now but also has a unit test. @ONG-YA please re-open if we missed something.

**Comment by ONG-YA** [comment]
> @ONG-YA can you check if the latest in master fixes your issue?

Solved！thanks guys.
