### ISSUE TITLE
Inject always fails with 'opentracing: Invalid Inject/Extract carrier' when falling back to TextMapWriter

### ISSUE THREAD

**Issue by ddtmachado** [openzipkin-contrib/zipkin-go-opentracing#151]
Looks like a PR recently introduced the support for `TextMapWriter` but forgot to return before the end of the function, that will return an error by default.

This is allowed because propagation tests are not checking for errors on the `Inject` function

Related to https://github.com/containous/traefik/issues/5646

**Comment by jcchavezs** [comment]
Closed by #150 & #152
