### ISSUE TITLE
dependencies versions should be upgraded to address security vulnerabilities

### ISSUE THREAD

**Issue by IF034Java** [openzipkin-contrib/zipkin-go-opentracing#158]
Is there any plans to release newer version of the `zipkin-go-opentracing` with upgraded dependencies?
The Veracode reports at least two vulnerabilities in the underlying dependencies see [gomega](https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/github-com-onsi-gomega/GO/GO/lid-886825/versions/v1.4.3) and [protobuf](https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/github-com-gogo-protobuf/GO/GO/lid-885410/versions/v1.2.0)

**Comment by jcchavezs** [comment]
Zipkin is a volunteering project, so you mind opening a PR with such
upgrades?

**Comment by IF034Java** [comment]
@jcchavezs 
I was trying to push my local branch but received error
`Permission to openzipkin-contrib/zipkin-go-opentracing.git denied to IF034Java`
Do I need any specific permissions to contribute to the `zipkin-go-opentracing` project?

**Comment by basvanbeek** [comment]
@IF034Java no you don't need special permissions to contribute, but you can't add branches directly to this repo. That indeed is reserved for maintainers only. 

Make a fork of this repo on your local github account and then push your updates to a branch there. Then you can create the pull request from your fork to this repo.

Thanks for helping out!

**Comment by IF034Java** [comment]
@jcchavezs @basvanbeek 
PR is created to address the [protobuf](https://sca.analysiscenter.veracode.com/vulnerability-database/libraries/github-com-gogo-protobuf/GO/GO/lid-885410/versions/v1.2.0) issue
see [here](https://github.com/openzipkin-contrib/zipkin-go-opentracing/pull/159)

**Comment by adrianosela** [comment]
Bump

**Comment by basvanbeek** [comment]
new release has been cut with zipkin-go v0.4.1 and opentracing-go v1.2.0.
