### ISSUE TITLE
Application using zipkin and kafka collector becomes very slow when kafka is down

### ISSUE THREAD

**Issue by cw-pratik** [openzipkin-contrib/zipkin-go-opentracing#63]
I was trying to setup zipkin in my production environment. Am using c# and golang clients of zipkin (zipkin4net & zipkin-go-opentracing). 
Also have setup kafka as the collector and cassandra as the storage. 
As zipkin is just used as a monitoring tool I would want it to work for small intervals. 
The problem is that while testing I stopped kafka for sometime to see if the apps are working fine. The c# apps kept working properly but the one with golang became very slow after submitting some spans (probably because it could not reach kafka). 

Also it occasionally gives a  panic error during sending the span to zipkin in the RecordSpan function of zipkin-recorder.go file. Its the last line of the function.

> _ = r.collector.Collect(span)

I think the spans should be dropped if kafka is not reachable.

Am using kafka 0.10.1

**Comment by basvanbeek** [comment]
Closing this as we're using the V2 transports from Zipkin Go now.
