### ISSUE TITLE
Adding traceid and parent span id as header from environment variables.

### ISSUE THREAD

**Issue by jprateekvmware** [openzipkin-contrib/zipkin-go-opentracing#66]
Hi ,
We are having gocli bosh and fly, currently we have got the tracing enabled by adding the library. We have got the trace_id and parent_span_id in the environment variables. Do we have option of reading those value from the env and having it added for all the HTTP request.

**Comment by adriancole** [comment]
This doesnt sound like something to implement in a core library. I suspect
even AWS Lambda tracing which does similiar does such as a layer custom for
that tool+env vs in the X-Ray sdk. Might be worth checking how others
prevent having to special case a single deployment env (ex maybe a context
hook)

**Comment by adriancole** [comment]
ps @ashutoshinvincible asked something similar too. answered here  https://gitter.im/openzipkin/zipkin?at=596ebec04bcd78af56c38a36

**Comment by adriancole** [comment]
from a convo on gitter, basically when a CLI boots up it needs to "extract" a context from env variables (or at least attempt to). I pointed to some test code, but maybe an example paste for how to extract or create a zipkin context for an explicit parent might be helpful.

**Comment by adriancole** [comment]
verified in AWS lambda: you have to read "X_AMZN_TRACE_ID" instead of the header "x-amzn-trace-id" to know your incoming parent. In brave, probably going to make this a utility function  for starters..

**Comment by jcchavezs** [comment]
> In brave, probably going to make this a utility function for starters.

@adriancole did you ended up implementing such a thing? if so, could you please point out the code?

**Comment by adriancole** [comment]
you can look at zipkin-aws there is a propagation helper there now.  yeah I think it will depend on the call site. you can look at what i did but also you can check out aws lambda sdk because they are primary user if this  my guess is they also have a utility that looks like an extractor

**Comment by basvanbeek** [comment]
Closing this as this logic is not a concern for the current bridge. If still a valid concern it should be opened at the [Zipkin Go](https://github.com/openzipkin/zipkin-go) repository
